name: Deploy s3 Bucket

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region'
        required: true
        default: 'ap-southeast-2'
#        keypair:
#         description: 'SSH Key Pair'
#         required: true

jobs:
  - name: Deploy to AWS CloudFormation
    uses: aws-actions/aws-cloudformation-github-deploy@v1
    with:
      name: MyStack
      template: infrastructure.yaml

